import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'


export default function Home() {
  return (
    <div>
<Head>
  <title>MY APP</title>
  <meta name="description" content="generated by create-next-app"/>
  <link rel='icon' href="/favicon.ico"/>
</Head>
<h1 className='text-3xl font-bold'>MY APP</h1>
</div>
  )   
}
